''' 
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

'''

def sum_fibonacci(num = 4000000): 
    output_sum = 0
    n_1 = 1
    n_2 = 1
    while True: 
        n = n_1 + n_2
        if n >= num: 
            break
        if n % 2 == 0: 
            output_sum += n
        n_2 = n_1
        n_1 = n
  
    return output_sum
    